climate_africa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('common.urls', 'common')),
    path('compose/', include('compose.urls', 'compose')),
    path('browse/', include('browse.urls', 'browse')),
    path('map/', include('map.urls', 'map')),
    path('help/', include('help.urls', 'help')),
    path('menu/', include('menu.urls', 'menu')),
    path('admin/', admin.site.urls),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

compose/urls.py
from django.urls import path
from compose import views

app_name = 'compose'

urlpatterns = [
    path('', views.init, name='init'),
    path('new/', views.new, name='new'),
]

map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path('', views.init, name='init'),
    path('alerts/', views.alerts, name='alerts'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.posts, name='posts'),
]

compose/forms.py
from django import forms
from django.forms.widgets import TextInput, Textarea, ClearableFileInput, SelectDateWidget
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

POST_TYPE_CHOICES = [
    (None, 'Post type (select one)'),
    ('extreme_weather_report', 'Extreme weather report'),
    ('resilience_project', 'Resilience project'),
    ('climate_justice_event', 'Climate justice event'),
    ('well_needed', 'Well needed'),
]

class PostForm(forms.Form):
    title = forms.CharField(widget=TextInput(attrs={'placeholder': 'Title'}))
    text = forms.CharField(widget=Textarea(attrs={'placeholder': 'Text'}))
    city = forms.CharField(max_length=80)
    image = forms.ImageField(required=False)
    type = forms.ChoiceField(choices=POST_TYPE_CHOICES)

    report_type = forms.CharField(max_length=40, required=False) # selectivity single -> tag
    report_impacts = forms.CharField(max_length=800, required=False) # selectivity multiple -> tags
    project_intentions = forms.CharField(max_length=800, required=False) # selectivity multiple -> tags
    event_date = forms.DateField(required=False, widget=SelectDateWidget())
    well_amount = forms.IntegerField(required=False, min_value=0, max_value=999999999)
    well_population = forms.IntegerField(required=False, min_value=0, max_value=999999999)

    def clean_city(self):
        city = self.cleaned_data['city']
        if (not city) or (city == 'null'):
            self.add_error('city', ValidationError('Please select a city from the dropdown'))
        return city

    # necessary?
    def clean_type(self):
        type = self.cleaned_data['type']
        if not type:
            self.add_error('type', ValidationError('Please select a post type from the dropdown'))
        return type

    def clean_report_type(self):
        type = self.cleaned_data['type']
        report_type = self.cleaned_data['report_type']
        if (not report_type) or (report_type == 'null'):
            if type == 'extreme_weather_report':
                self.add_error('report_type', ValidationError('Please select an extreme weather type from the dropdown'))
            else:
                return None
        return report_type

    def clean_report_impacts(self):
        type = self.cleaned_data['type']
        report_impacts = self.cleaned_data['report_impacts']
        if (not report_impacts) or (report_impacts == 'null'):
            return None
        return report_impacts

    def clean_project_intentions(self):
        type = self.cleaned_data['type']
        project_intentions = self.cleaned_data['project_intentions']
        if (not project_intentions) or (project_intentions == 'null'):
            return None
        return project_intentions

    def clean_event_date(self):
        type = self.cleaned_data['type']
        event_date = self.cleaned_data['event_date']
        if type == 'climate_justice_event':
            if not event_date:
                self.add_error('event_date', ValidationError('Please select an event date'))
        return event_date

    def clean_well_amount(self):
        type = self.cleaned_data['type']
        well_amount = self.cleaned_data['well_amount']
        if type == 'well_needed':
            if not well_amount:
                self.add_error('well_amount', ValidationError('Please enter how much the well will cost (USD)'))
        return well_amount

    def clean_well_population(self):
        type = self.cleaned_data['type']
        well_population = self.cleaned_data['well_population']
        if type == 'well_needed':
            if not well_population:
                self.add_error('well_population', ValidationError('Please enter how many people the well will serve'))
        return well_population

compose/views.py
from django.shortcuts import render, redirect
from compose.forms import PostForm
from common.models import Post, Tag, Image
from cities_light.models import City, Country

from django.utils.safestring import mark_safe
import json

def init(request):
    return redirect('compose:new')

def new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            city_name = json.loads(form.cleaned_data['city'])['text']
            city_object = City.objects.get(name=city_name)

            post = Post.objects.create(
                user=request.user,
                title=form.cleaned_data.get('title'),
                text=form.cleaned_data.get('text'),
                city=city_object,
                type=form.cleaned_data.get('type'),
                event_date = form.cleaned_data.get('event_date'),
                well_amount = form.cleaned_data.get('well_amount'),
                well_population = form.cleaned_data.get('well_population')
            )

            if form.cleaned_data.get('image'):
                image = Image.objects.create(
                    post=post,
                    order_in_post=1,
                    image=form.cleaned_data.get('image'),
                )

            if form.cleaned_data['report_type']:
                report_type_dict = json.loads(form.cleaned_data['report_type'])
                report_type_filter = Tag.objects.filter(
                    name=report_type_dict['text'],
                    type='report_type',
                )
                if report_type_filter.exists():
                    report_type_tag = report_type_filter.first()
                else:
                    report_type_tag = Tag.objects.create(
                        name=report_type_dict['text'],
                        type='report_type',
                        is_starter=False,
                    )
                post.tags.add(report_type_tag)

            for report_impact_dict in json.loads(form.cleaned_data['report_impacts']):
                report_impact_filter = Tag.objects.filter(
                    name=report_impact_dict['text'],
                    type='report_impact',
                )
                if report_impact_filter.exists():
                    report_impact_tag = report_impact_filter.first()
                else:
                    report_impact_tag = Tag.objects.create(
                        name=report_impact_dict['text'],
                        type='report_impact',
                        is_starter=False,
                    )
                post.tags.add(report_impact_tag)

            for project_intention_dict in json.loads(form.cleaned_data['project_intentions']):
                project_intention_filter = Tag.objects.filter(
                    name=project_intention_dict['text'],
                    type='project_intention',
                )
                if project_intention_filter.exists():
                    project_intention_tag = project_intention_filter.first()
                else:
                    project_intention_tag = Tag.objects.create(
                        name=project_intention_dict['text'],
                        type='project_intention',
                        is_starter=False,
                    )
                post.tags.add(project_intention_tag)

            return redirect('map:posts', post_id=post.id) # replace with animation page
    else:
        form = PostForm()

    country_city_names = [{
        'text': country.name,
        'children': [{
            'id': city.name + '; ' + country.name,
            'text': city.name,
        } for city in country.city_set.all()]
    } for country in Country.objects.filter(continent='AF')]
    country_city_names_json = mark_safe(json.dumps(country_city_names))

    if request.user.profile.default_city:
        default_city = request.user.profile.default_city
        default_city_object = {
            'id': default_city.name + '; ' + default_city.country.name,
            'text': default_city.name,
        }
    else:
        default_city_object = None
    default_city_object_json = mark_safe(json.dumps(default_city_object))

    report_type_names = [tag.name for tag in Tag.objects.filter(type='report_type', is_starter=True)]
    report_type_names_json = mark_safe(json.dumps(report_type_names))
    report_impact_names = [tag.name for tag in Tag.objects.filter(type='report_impact', is_starter=True)]
    report_impact_names_json = mark_safe(json.dumps(report_impact_names))
    project_intention_names = [tag.name for tag in Tag.objects.filter(type='project_intention', is_starter=True)]
    project_intention_names_json = mark_safe(json.dumps(project_intention_names))

    context = {
        'form': form,
        'city_names': country_city_names_json,
        'default_city_object': default_city_object_json,
        'report_type_names': report_type_names_json,
        'report_impact_names': report_impact_names_json,
        'project_intention_names': project_intention_names_json,
    }
    return render(request, 'compose/new.html', context=context)

compose/templates/compose/new.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static 'compose/css/new_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static 'common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript'>
    var cityNames = {{ city_names }};
    var defaultCityObject = {{ default_city_object }};
    var reportTypeNames = {{ report_type_names }};
    var reportImpactNames = {{ report_impact_names }};
    var projectIntentionNames = {{ project_intention_names }};
</script>
<script type='text/javascript' src='{% static 'compose/js/new_main.js' %}'></script>
{% endblock %}


{% block content %}
<div class='container-fluid'>
    <div id='compose'>
        <form id='new-form' action='{% url 'compose:new' %}' method='post' enctype='multipart/form-data'>
            {% csrf_token %}
            <input type='hidden' id='city-input-hidden' name='city'>
            <input type='hidden' id='report-type-input-hidden' name='report_type'>
            <input type='hidden' id='report-impacts-input-hidden' name='report_impacts'>
            <input type='hidden' id='project-intentions-input-hidden' name='project_intentions'>
            {{ form.non_field_errors }}
            <div id='content-mat' class='custom-shadow mat'>
                <div id='image-wrapper'>
                    <label id='image-label' for='id_image'>Image:</label>
                    {{ form.image }}
                    {{ form.image.errors }}
                </div>
                <div id='title-wrapper'>
                    {{ form.title }}
                    {{ form.title.errors }}
                </div>
                <div id='text-wrapper'>
                    {{ form.text }}
                    {{ form.text.errors }}
                </div>
            </div>
            <div id='general-meta-mat' class='mat custom-shadow'>
                <div id='city-wrapper'>
                    <div id='city' class='selectivity-target'></div>
                    {{ form.city.errors }}
                </div>
                <div id='type-wrapper'>
                    {{ form.type }}
                    {{ form.type.errors }}
                </div>
            </div>
            <!-- can probably remove -->
            <div id='report-meta-mat' class='mat custom-shadow'>
                <div id='report-type-wrapper'>
                    <div id='report-type' class='selectivity-target'></div>
                    {{ form.report_type.errors }}
                </div>
                <div id='report-impacts-wrapper'>
                    <div id='report-impacts'></div>
                    {{ form.report_impacts.errors }}
                </div>
            </div>
            <div id='project-meta-mat' class='mat custom-shadow'>
                <div id='project-intentions-wrapper'>
                    <div id='project-intentions' class='selectivity-target'></div>
                    {{ form.project_intentions.errors }}
                </div>
            </div>
            <div id='event-meta-mat' class='mat custom-shadow'>
                <div id='event-date-wrapper'>
                    {{ form.event_date }}
                    {{ form.event_date.errors }}
                </div>
            </div>
            <div id='well-meta-mat' class='mat custom-shadow'>
                <div id='well-amount-wrapper'>
                    <label id='well-amount-label' for='id_well_amount'>Amount needed (USD): $</label>
                    {{ form.well_amount }}
                    {{ form.well_amount.errors }}
                </div>
                <div id='well-population-wrapper'>
                    <label id='well-population-label' for='id_well_population'>Population served:</label>
                    {{ form.well_population }}
                    {{ form.well_population.errors }}
                </div>
            </div>
            <button id='submit-button' type='submit' class='custom-shadow button'>Submit</button>
        </form>
    </div>
</div>
{% endblock %}