browse/urls.py
from django.urls import path
from browse import views

app_name = 'browse'

urlpatterns = [
    path('', views.init, name='init'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.post, name='post'),
    path('profiles/<int:user_id>/', views.profile, name='profile'),
]

climate_africa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('common.urls', 'common')),
    path('compose/', include('compose.urls', 'compose')),
    path('browse/', include('browse.urls', 'browse')),
    path('map/', include('map.urls', 'map')),
    path('help/', include('help.urls', 'help')),
    path('menu/', include('menu.urls', 'menu')),
    path('admin/', admin.site.urls),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

common/urls.py
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    path('', views.init, name='init'),
    path('welcome/', views.welcome, name='welcome'),
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

compose/urls.py
from django.urls import path
from compose import views

app_name = 'compose'

urlpatterns = [
    path('', views.init, name='init'),
    path('new/', views.new, name='new'),
]

help/urls.py
from django.urls import path
from help import views

app_name = 'help'

urlpatterns = [
    path('', views.init, name='init'),
    path('select', views.select, name='select'),
]

map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path('', views.init, name='init'),
    path('alerts/', views.alerts, name='alerts'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.posts, name='posts'),
]

menu/urls.py
from django.urls import path
from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.init, name='init'),
    path('select/', views.select, name='select'),
    path('change-info/', views.change_info, name='change_info'),
    path('change-password/', views.change_password, name='change_password'),
]

common/models.py
from django.db import models
from django.contrib.auth.models import User # unsure how to do this with string, my preference
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

# ensures that multiple posts can upload same images without backblaze grouping them.
def image_upload_path(instance, filename):
    return f'users/{instance.post.user.id}/posts/{instance.post.id}/images/{filename}'

# Refactor idea: change to PostImage, to mesh with ProfileImage
class Image(models.Model):
    post = models.ForeignKey('common.Post', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload_path)
    order_in_post = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f'ID: {self.id}, post title: {self.post.title}'

@receiver(post_delete, sender=Image)
def remove_file_from_cloud(sender, instance, using, **kwargs):
    instance.image.delete(save=False)

POST_TYPE_CHOICES = [
    ('extreme_weather_report', 'Extreme weather report'),
    ('resilience_project', 'Resilience project'),
    ('climate_justice_event', 'Climate justice event'),
    ('well_needed', 'Well needed'),
]

class Post(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=160)
    text = models.TextField()
    tags = models.ManyToManyField('common.Tag', related_name='users')
    city = models.ForeignKey('cities_light.City', on_delete=models.PROTECT)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    type = models.CharField(max_length=40, choices=POST_TYPE_CHOICES)
    event_date = models.DateField(null=True, blank=True)
    well_amount = models.PositiveIntegerField(null=True, blank=True)
    well_population = models.PositiveIntegerField(null=True, blank=True)


    @property
    def all_images(self):
        return self.image_set.all()

    @property
    def first_image(self):
        return self.image_set.order_by('order_in_post').first()

    @property
    def n_supporters(self):
        return self.supporters.count()

    def __str__(self):
        return f'ID: {self.id}, title: {self.title}'

TAG_TYPE_CHOICES = [
    ('report_type', 'Extreme weather report type'),
    ('report_impact', 'Extreme weather report impact'),
    ('project_intention', 'Resilience project intention'),
    ('other', 'Other'),
]

class Tag(models.Model):
    name = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    is_starter = models.BooleanField(default=False, blank=True)
    type = models.CharField(max_length=40, choices=TAG_TYPE_CHOICES)

    def __str__(self):
        return f'ID: {self.id}, name: {self.name}, is_starter: {str(self.is_starter)}'

def user_image_upload_path(instance, filename):
    return f'users/{instance.user.id}/user_image/{filename}'


class UserImage(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    image = models.ImageField(upload_to=user_image_upload_path)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f'ID: {self.id}, username: {self.user.username}'

# would be better to have abstract w subclasses, but tricky with existing migrations
# for now profile will have fields for organizations alongside fields for people profiles
class Profile(models.Model):
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    default_city = models.ForeignKey('cities_light.City', on_delete=models.PROTECT, null=True, blank=True) # change to required later
    is_organization = models.BooleanField(default=False)
    bio = models.TextField(null=True, blank=True) # suggested for orgs, maybe people too
    website = models.CharField(max_length=160, null=True, blank=True) # suggested for organizations
    email = models.EmailField(null=True, blank=True)

    @property
    def user_image_or_none(self):
        user_image = UserImage.objects.filter(user=self.user)
        if user_image.exists():
            return user_image.latest('created_at')
        else:
            return None

    @property
    def n_supporters(self):
        return self.user.supporters.count()

    def __str__(self):
        return f'ID: {self.id}, username: {self.user.username}'

    # might not need to be part of this class
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    # might not need to be part of this class
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

# DEPRECATED
class Support(models.Model):
    supporter = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='supports_made')
    supported_post = models.ForeignKey('common.Post', on_delete=models.CASCADE, null=True, blank=True, related_name='supporters')
    supported_user = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True, related_name='supporters')
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    @property
    def for_post(self):
        return self.supported_post != None

    @property
    def for_user(self):
        return self.supported_user != None

    def __str__(self):
        if self.for_post and self.for_user:
            return f'ID: {self.id}, supporter: {self.supporter.username}, ERROR support has post AND user. Post: {self.supported_post.title}; user: {self.supported_user.username}'
        elif self.for_post:
            return f'ID: {self.id}, supporter: {self.supporter.username}, supported post title: {self.supported_post.title}'
        elif self.for_user:
            return f'ID: {self.id}, supporter: {self.supporter.username}, supported user username: {self.supported_user.username}'
        else:
            return f'ID: {self.id}, supporter: {self.supporter.username}, ERROR support has neither supported post nor supported user.'

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput, Textarea, CheckboxInput, NullBooleanSelect, RadioSelect, EmailInput, ClearableFileInput
from django.core.exceptions import ValidationError

IS_ORGANIZATION_CHOICES = [
    (None, '(select one)'),
    (False, 'myself'),
    (True, 'my organization'),
]

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))
    password2 = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Confirm password'}))

    is_organization = forms.ChoiceField(choices=IS_ORGANIZATION_CHOICES)#widget=CustomNullBooleanSelect())#(choices=is_organization_choices))#widget=CheckboxInput(attrs={'class': 'form-check-input'}))
    name = forms.CharField(max_length=90, widget=TextInput(attrs={'placeholder': 'Name'}))
    email = forms.EmailField(required=False, widget=EmailInput(attrs={'placeholder': 'Email (optional)'}))
    bio = forms.CharField(required=False, widget=Textarea(attrs={'placeholder': 'Bio (optional)'}))
    default_city = forms.CharField(max_length=80, required=False)
    user_image = forms.ImageField(required=False)
    website = forms.CharField(max_length=160, required=False, widget=TextInput(attrs={'placeholder': 'Website (optional)'}))

    def clean_is_organization(self):
        is_organization = self.cleaned_data['is_organization']
        if is_organization == 'None':
            self.add_error('is_organization', ValidationError('Please select who this profile is for'))
            return None
        elif is_organization == 'True':
            return True
        elif is_organization == 'False':
            return False
        print('Error: unexpected is_organization value')
        return is_organization

    def clean_name(self):
        name = self.cleaned_data['name']
        if name == '':
            self.add_error('name', ValidationError('Please enter a name'))#, code='none_selected')
            return None
        else:
            return name

    def clean_email(self):
        email = self.cleaned_data['email']
        if email == '':
            return None
        else:
            return email

    def clean_bio(self):
        bio = self.cleaned_data['bio']
        if bio == '':
            return None
        else:
            return bio

    def clean_default_city(self):
        default_city = self.cleaned_data['default_city']
        if default_city == '' or default_city == 'null':
            self.add_error('default_city', ValidationError('Please select a default city from the dropdown'))#, code='none_selected')
            return None
        else:
            return default_city

    def clean_website(self):
        website = self.cleaned_data['website']
        if website == '':
            return None
        else:
            return website

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))

common/views.py
from django.contrib import auth
from django.contrib.auth.models import User
from common.forms import CustomUserCreationForm, CustomAuthenticationForm
from django.shortcuts import render, redirect
from cities_light.models import City, Country
from django.utils.safestring import mark_safe
import json

from common.models import Profile, UserImage

def init(request):
    return redirect('browse:init')

def welcome(request):
    context = {

    }
    return render(request, 'common/welcome.html', context=context)

def join(request):
    if not request.user.is_authenticated:
        next = request.GET.get('next')
        if next is None:
            next = '/'

        if request.method == 'POST':
            form = CustomUserCreationForm(request.POST, request.FILES)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                user = User.objects.create_user(
                    username=username,
                    password=password,
                )

                city_name = json.loads(form.cleaned_data['default_city'])['text']
                city_object = City.objects.get(name=city_name)
                profile = user.profile
                profile.default_city = city_object
                profile.is_organization = form.cleaned_data.get('is_organization')
                profile.bio = form.cleaned_data.get('bio')
                profile.website = form.cleaned_data.get('website')
                profile.email = form.cleaned_data.get('email')
                profile.name = form.cleaned_data.get('name')
                profile.save()

                if form.cleaned_data.get('user_image'):
                    image = UserImage.objects.create(
                        user=user,
                        image=form.cleaned_data.get('user_image')
                    )

                user = auth.authenticate(username=username, password=password)
                auth.login(request, user)
                return redirect(next)
        else:
            form = CustomUserCreationForm()

        country_city_names = [{
            'text': country.name,
            'children': [{
                'id': city.name + '; ' + country.name,
                'text': city.name,
            } for city in country.city_set.all()]
        } for country in Country.objects.filter(continent='AF')]
        country_city_names_json = mark_safe(json.dumps(country_city_names))

        context = {
            'form': form,
            'next': next,
            'city_names': country_city_names_json,
        }
        return render(request, 'common/join.html', context=context)
    else:
        return redirect('/')

def login(request):
    if not request.user.is_authenticated:
        next = request.GET.get('next')
        if next is None:
            next = '/'

        if request.method == 'POST':
            form = CustomAuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = auth.authenticate(username=username, password=password)
                if user is not None:
                    auth.login(request, user)
                    return redirect(next)
        else:
            form = CustomAuthenticationForm()
        context = {
            'form': form,
            'next': next,
        }
        return render(request, 'common/login.html', context=context)
    else:
        print('user is authenticated')
        return redirect('common:init')

def logout(request):
    auth.logout(request)
    return redirect('common:init')

common/templates/common/base.html
{% load bootstrap4 %}
{% load static %}
{% load tz_detect %}
<!DOCTYPE html>

<html>
<head>
    <meta charset='utf-8'>
    <title>Climate Africa</title>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'common/img/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'common/img/favicon-16x16.png' %}">

    {% bootstrap_css %}
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
    <link rel='stylesheet' href='{% static 'common/css/style.css' %}'>
    {% block content_style %}{% endblock %}

    {% bootstrap_javascript jquery='full' %}
    <script type='text/javascript' src='{% static 'common/js/main.js' %}'></script>
    {% block content_script %}{% endblock %}

    {% tz_detect %}
</head>
<body>
    {% include 'common/header.html' %}
    <div id='content-wrapper'>{% block content %}{% endblock %}</div>
    <div id='phone'>
        <img id='phone-mockup' src='{% static 'common/img/phone_mockup_darkborder.png' %}' alt='phone mockup'/>
        <img id='phone-mockup-cutoff' src='{% static 'common/img/phone_mockup_cutoff.png' %}' alt='phone mockup cutoff'/>
        <img id='phone-background' src='{% static 'common/img/phone_background_grey_xtreme.png' %}' alt='phone background'/>
        <div id='phone-screen'>
        </div>
    </div>
</body>
</html>

common/templates/common/header.html
{% load static %}

<link rel='stylesheet' href='{% static 'common/css/header_style.css' %}'>
<script type='text/javascript' src='{% static 'common/js/header_main.js' %}'></script>

<div id='header' class='custom-shadow-lg'>
    <div class='icon-placement-wrapper'>
        <a href='{% url 'compose:init' %}'>
            {% if request.resolver_match.app_name == 'compose' %}
            <div class='icon-wrapper-selected'><img id='icon-compose' class='icon' src='{% static 'common/img/compose_gold.png' %}' alt='compose icon selected'/></div>
            {% else %}
            <div class='icon-wrapper-unselected'><img id='icon-compose' class='icon' src='{% static 'common/img/compose_grey.png' %}' alt='compose icon unselected'/></div>
            {% endif %}
        </a>
    </div>
    <div class='icon-placement-wrapper'>
        <a href='{% url 'browse:init' %}'>
            {% if request.resolver_match.app_name == 'browse' %}
            <div class='icon-wrapper-selected'><img id='icon-browse' class='icon' src='{% static 'common/img/browse_gold.png' %}' alt='browse icon selected'/></div>
            {% else %}
            <div class='icon-wrapper-unselected'><img id='icon-browse' class='icon' src='{% static 'common/img/browse_grey.png' %}' alt='browse icon unselected'/></div>
            {% endif %}
        </a>
    </div>
    <div class='icon-placement-wrapper'>
        <a href='{% url 'map:init' %}'>
            {% if request.resolver_match.app_name == 'map' %}
            <div class='icon-wrapper-selected'><img id='icon-map' class='icon' src='{% static 'common/img/map_gold.png' %}' alt='map icon selected'/></div>
            {% else %}
            <div class='icon-wrapper-unselected'><img id='icon-map' class='icon' src='{% static 'common/img/map_grey.png' %}' alt='map icon unselected'/></div>
            {% endif %}
        </a>
    </div>
    <div class='icon-placement-wrapper'>
        <a href='{% url 'help:init' %}'>
            {% if request.resolver_match.app_name == 'help' %}
            <div class='icon-wrapper-selected'><img id='icon-map' class='icon' src='{% static 'common/img/help_gold.png' %}' alt='help icon selected'/></div>
            {% else %}
            <div class='icon-wrapper-unselected'><img id='icon-map' class='icon' src='{% static 'common/img/help_grey.png' %}' alt='help icon unselected'/></div>
            {% endif %}
        </a>
    </div>
    <div class='icon-placement-wrapper'>
        <a href='{% url 'menu:init' %}'>
            {% if request.resolver_match.app_name == 'menu' %}
            <div class='icon-wrapper-selected'><img id='icon-menu' class='icon' src='{% static 'common/img/menu_gold.png' %}' alt='menu icon selected'/></div>
            {% else %}
            <div class='icon-wrapper-unselected'><img id='icon-menu' class='icon' src='{% static 'common/img/menu_grey.png' %}' alt='menu icon unselected'/></div>
            {% endif %}
        </a>
    </div>
</div>

common/templates/common/join.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static ' common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static ' common/css/join_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static ' common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript'>
    var cityNames = {{ city_names }};
</script>
<script type='text/javascript' src='{% static ' common/js/join_main.js' %}'></script>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='join' class='main'>
        <form id='join-form' action='{% url ' common:join' %}?next={{ next }}' method='post'
            enctype='multipart/form-data'>
            {% csrf_token %}
            <input type='hidden' id='default-city-input-hidden' name='default_city'>
            {{ form.non_field_errors }}
            <div id='username-mat' class='mat custom-shadow'>
                <div class="form-group">
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
            </div>
            <div id='password-mat' class='mat custom-shadow'>
                <div class="form-group">
                    {{ form.password1 }}
                    {{ form.password1.errors }}
                </div>
                <div class="form-group">
                    {{ form.password2 }}
                    {{ form.password2.errors }}
                </div>
            </div>
            <div id='is-organization-mat' class='mat custom-shadow'>
                <div id='is-organization-wrapper'>
                    <label id='is-organization-label' for='id_is_organization'>This profile is for</label>
                    {{ form.is_organization }}
                    {{ form.is_organization.errors }}
                </div>
            </div>
            <div id='additional-info-mat' class='mat custom-shadow'>
                <div id='name-wrapper'>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div id='default-city-wrapper'>
                    <div id='default-city'></div>
                    {{ form.default_city.errors }}
                </div>
                <div id='email-wrapper'>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div id="bio-wrapper">
                    {{ form.bio }}
                    {{ form.bio.errors }}
                </div>
                <div id='website-wrapper'>
                    {{ form.website }}
                    {{ form.website.errors }}
                </div>
                <div id='user-image-wrapper'>
                    <label id='user-image-label' for='id_user_image'>Image:</label>
                    {{ form.user_image }}
                    {{ form.user_image.errors }}
                </div>
            </div>
            <button id='submit-button' type='submit' class='button custom-shadow'>Join ClimateJustice4Africa</button>
        </form>
        <a href='{% url ' common:login' %}?next={{ next }}'>
            <div id='login-link'>I already have an account</div>
        </a>
    </div>
</div>
{% endblock %}

common/templates/common/login.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/login_style.css' %}'>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='login' class='main'>
        <form action='{% url 'common:login' %}?next={{ next }}' method='post'>
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div id='username-password-mat' class='custom-shadow'>
                <div class="form-group">
                    {{ form.username }}
                    {{ form.username.errors }}
                </div>
                <div class="form-group">
                    {{ form.password }}
                    {{ form.password.errors }}
                </div>
            </div>
            <button id='submit-button' type='submit' class="custom-shadow">Log in</button>
        </form>
        <a href='{% url 'common:join' %}?next={{ next }}'><div id='join-link'>I don't have an account</div></a>
    </div>
</div>
{% endblock %}