climate_africa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('common.urls', 'common')),
    path('compose/', include('compose.urls', 'compose')),
    path('browse/', include('browse.urls', 'browse')),
    path('map/', include('map.urls', 'map')),
    path('help/', include('help.urls', 'help')),
    path('menu/', include('menu.urls', 'menu')),
    path('admin/', admin.site.urls),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

common/urls.py
from django.urls import path
from common import views

app_name = 'common'

urlpatterns = [
    path('', views.init, name='init'),
    path('welcome/', views.welcome, name='welcome'),
    path('join/', views.join, name='join'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path('', views.init, name='init'),
    path('alerts/', views.alerts, name='alerts'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.posts, name='posts'),
]

menu/urls.py
from django.urls import path
from menu import views

app_name = 'menu'

urlpatterns = [
    path('', views.init, name='init'),
    path('select/', views.select, name='select'),
    path('change-info/', views.change_info, name='change_info'),
    path('change-password/', views.change_password, name='change_password'),
]

menu/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms.widgets import PasswordInput, TextInput, Textarea, CheckboxInput, NullBooleanSelect, RadioSelect, EmailInput, ClearableFileInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm

class ChangeInfoForm(forms.Form):
    new_username = forms.CharField(widget=TextInput(attrs={'placeholder': 'New username'}))

    new_name = forms.CharField(max_length=90, widget=TextInput(attrs={'placeholder': 'New name'}))
    new_email = forms.EmailField(required=False, widget=EmailInput(attrs={'placeholder': 'New email (leave blank to remove)'}))
    new_bio = forms.CharField(required=False, widget=Textarea(attrs={'placeholder': 'New bio (leave blank to remove)'}))
    new_default_city = forms.CharField(max_length=80, required=False)
    new_user_image = forms.ImageField(required=False)
    new_website = forms.CharField(max_length=160, required=False, widget=TextInput(attrs={'placeholder': 'New website (leave blank to remove)'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ChangeInfoForm, self).__init__(*args, **kwargs)

    def clean_new_username(self):
        new_username = self.cleaned_data['new_username']
        if new_username == '':
            self.add_error('new_username', ValidationError('Please enter a new username or leave as-is'))#, code='none_selected')
            return None
        elif User.objects.exclude(id=self.user.id).filter(username=new_username).exists():
            self.add_error('new_username', ValidationError('New username is already in use'))#, code='none_selected')
        else:
            return new_username

    def clean_new_name(self):
        new_name = self.cleaned_data['new_name']
        if new_name == '':
            self.add_error('new_name', ValidationError('Please enter a new name or leave as-is'))#, code='none_selected')
            return None
        else:
            return new_name

    def clean_new_email(self):
        new_email = self.cleaned_data['new_email']
        if new_email == '':
            return None
        else:
            return new_email

    def clean_bio(self):
        new_bio = self.cleaned_data['new_bio']
        if new_bio == '':
            return None
        else:
            return new_bio

    def clean_new_default_city(self):
        new_default_city = self.cleaned_data['new_default_city']
        if new_default_city == '' or new_default_city == 'null':
            return None
        else:
            return new_default_city

    def clean_new_website(self):
        new_website = self.cleaned_data['new_website']
        if new_website == '':
            return None
        else:
            return new_website

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=PasswordInput(attrs={'placeholder':'New password'}))
    new_password2 = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Confirm new password'}))

menu/views.py
from django.shortcuts import render, redirect
from menu.forms import ChangeInfoForm, CustomSetPasswordForm
# from django.contrib.auth.forms import SetPasswordForm, PasswordChangeForm
from django.contrib import auth
from django.contrib.auth.models import User
from cities_light.models import City, Country
from django.utils.safestring import mark_safe
import json
from common.models import Profile, UserImage

def init(request):
    return redirect('menu:select')

def select(request):
    context = {
    }
    return render(request, 'menu/select.html', context=context)

def change_info(request):
    if request.method == 'POST':
        form = ChangeInfoForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            user = request.user
            user.username = form.cleaned_data.get('new_username')
            user.save()

            new_city_name = json.loads(form.cleaned_data['new_default_city'])['text']
            new_city_object = City.objects.get(name=new_city_name)
            profile = user.profile
            profile.default_city = new_city_object
            profile.name = form.cleaned_data.get('new_name')
            profile.email = form.cleaned_data.get('new_email')
            profile.bio = form.cleaned_data.get('new_bio')
            profile.website = form.cleaned_data.get('new_website')
            profile.save()

            # TODO allow an option to remove image entirely
            new_image = form.cleaned_data.get('new_user_image')
            if new_image:
                image_object, created = UserImage.objects.get_or_create(user=user)
                image_object.image = form.cleaned_data.get('new_user_image')
                image_object.save()

            return redirect('menu:select')
    else:
        form = ChangeInfoForm(user=request.user)

    country_city_names = [{
        'text': country.name,
        'children': [{
            'id': city.name + '; ' + country.name,
            'text': city.name,
        } for city in country.city_set.all()]
    } for country in Country.objects.filter(continent='AF')]
    country_city_names_json = mark_safe(json.dumps(country_city_names))

    profile = request.user.profile
    old_info = {
        'username': request.user.username,
        'name': profile.name,
        'email': profile.email if profile.email else '',
        'bio': profile.bio if profile.bio else '',
        'default_city_id': profile.default_city.name + '; ' + profile.default_city.country.name if profile.default_city else None,
        'user_image_url': profile.user_image_or_none.image.url if profile.user_image_or_none else '',
        'website': profile.website if profile.website else '',
    }
    old_info_json = mark_safe(json.dumps(old_info))
    context = {
        'form': form,
        'city_names': country_city_names_json,
        'old_info': old_info_json,
    }
    return render(request, 'menu/change_info.html', context=context)

def change_password(request):
    if request.method == 'POST':
        form = CustomSetPasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            auth.update_session_auth_hash(request, user)
            return redirect('menu:select')
    else:
        form = CustomSetPasswordForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'menu/change_password.html', context=context)

menu/templates/menu/change_info.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static 'menu/css/change_info_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static 'common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript'>
    var cityNames = {{ city_names }};
    var oldInfo = {{ old_info }};
</script>
<script type='text/javascript' src='{% static 'menu/js/change_info_main.js' %}'></script>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='change-info' class='main'>
        <form id='change-info-form' action='{% url 'menu:change_info' %}' method='post' enctype='multipart/form-data'>
            {% csrf_token %}
            <input type='hidden' id='new-default-city-input-hidden' name='new_default_city'>
            {{ form.non_field_errors }}
            <div id='new-username-mat' class='mat custom-shadow'>
                <div class="form-group">
                    {{ form.new_username }}
                    {{ form.new_username.errors }}
                </div>
            </div>
            <div id='additional-info-mat' class='mat custom-shadow'>
                <div id='new-name-wrapper'>
                    {{ form.new_name }}
                    {{ form.new_name.errors }}
                </div>
                <div id='new-default-city-wrapper'>
                    <div id='new-default-city'></div>
                    {{ form.new_default_city.errors }}
                </div>
                <div id='new-email-wrapper'>
                    {{ form.new_email }}
                    {{ form.new_email.errors }}
                </div>
                <div id="new-bio-wrapper">
                    {{ form.new_bio }}
                    {{ form.new_bio.errors }}
                </div>
                <div id='new-website-wrapper'>
                    {{ form.new_website }}
                    {{ form.new_website.errors }}
                </div>
                <div id='new-user-image-wrapper'>
                    <label id='new-user-image-label' for='id_new_user_image'>New image:</label>
                    {{ form.new_user_image }}
                    {{ form.new_user_image.errors }}
                </div>
            </div>
            <button id='submit-button' type='submit' class='button custom-shadow'>Update information</button>
        </form>
    </div>
</div>
{% endblock %}

menu/templates/menu/change_password.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'menu/css/change_password_style.css' %}'>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='change-password' class='main'>
        <form id='change-password-form' action='{% url 'menu:change_password' %}' method='post'>
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div id='new-password-mat' class='mat custom-shadow'>
                <div class="form-group">
                    {{ form.new_password1 }}
                    {{ form.new_password1.errors }}
                </div>
                <div class="form-group">
                    {{ form.new_password2 }}
                    {{ form.new_password2.errors }}
                </div>
            </div>
            <button id='submit-button' type='submit' class='button custom-shadow'>Update password</button>
        </form>
    </div>
</div>
{% endblock %}

menu/templates/menu/select.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'menu/css/select_style.css' %}'>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='menu' class='main'>
        <div class='row h-100'>
            <div id='selection-wrapper' class='col my-auto'>
                <a href='{% url 'common:logout' %}'><div id='log-out' class='custom-shadow option button'>Log Out</div></a>
                <a href='{% url 'menu:change_info' %}'><div id='change-info' class='custom-shadow option button'>Change Information</div></a>
                <a href='{% url 'menu:change_password' %}'><div id='change-password' class='custom-shadow option button'>Change Password</div></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}