browse/urls.py
from django.urls import path
from browse import views

app_name = 'browse'

urlpatterns = [
    path('', views.init, name='init'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.post, name='post'),
    path('profiles/<int:user_id>/', views.profile, name='profile'),
]

climate_africa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('', include('common.urls', 'common')),
    path('compose/', include('compose.urls', 'compose')),
    path('browse/', include('browse.urls', 'browse')),
    path('map/', include('map.urls', 'map')),
    path('help/', include('help.urls', 'help')),
    path('menu/', include('menu.urls', 'menu')),
    path('admin/', admin.site.urls),
    url(r'^tz_detect/', include('tz_detect.urls')),
]

map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path('', views.init, name='init'),
    path('alerts/', views.alerts, name='alerts'),
    path('posts/', views.posts, name='posts'),
    path('posts/<int:post_id>/', views.posts, name='posts'),
]

browse/forms.py
from django import forms

SEARCH_TYPE_CHOICES = [
    (None, 'Post type'),
    ('extreme_weather_report', 'Extreme weather report'),
    ('resilience_project', 'Resilience project'),
    ('climate_justice_event', 'Climate justice event'),
    ('well_needed', 'Well needed'),
]

SEARCH_SORT_BY_CHOICES = [
    ('new', 'New'),
    ('recommended', 'Recommended'),
]

class SearchForm(forms.Form):
    query = forms.CharField(required=False, max_length=40)
    city = forms.CharField(required=False, max_length=80)
    type = forms.ChoiceField(required=False, choices=SEARCH_TYPE_CHOICES)
    sort_by = forms.ChoiceField(choices=SEARCH_SORT_BY_CHOICES)

    def clean_city(self):
        city = self.cleaned_data['city']
        if city == 'null':
            return None
        return city

browse/views.py
from django.shortcuts import render, redirect
from common.models import Post, Support, UserImage, Tag
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from browse.forms import SearchForm
from django.utils.safestring import mark_safe
from django.contrib.postgres.search import SearchQuery, SearchVector
from cities_light.models import City, Country

import json

def init(request):
    return redirect('browse:posts')

def posts(request):
    showing_results = False
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            showing_results = True
            if form.cleaned_data['query']:
                query = SearchQuery(form.cleaned_data['query'])
                vector = SearchVector('title', 'text', 'user__profile__name')
                # this is where we'd adjust sort order, if that was supported
                posts = Post.objects.annotate(search=vector).filter(search=query)
            else:
                posts = Post.objects.all()

            if form.cleaned_data['type']:
                posts = posts.filter(type=form.cleaned_data['type'])

            if form.cleaned_data['city']:
                city_name = json.loads(form.cleaned_data['city'])['text']
                city_object = City.objects.get(name=city_name)
                posts = posts.filter(city=city_object)

            posts = posts.order_by('-created_at')

    else:
        form = SearchForm()
        posts = Post.objects.all().order_by('-created_at')

    # won't stand up to huge datasets; should eventually be done with fancy query
    available_country_city_names_dict = {}
    for post in Post.objects.all():
        city_name = post.city.name
        country_name = post.city.country.name
        if country_name in available_country_city_names_dict:
            if not city_name in available_country_city_names_dict[country_name]:
                available_country_city_names_dict[country_name].append(city_name)
        else:
            available_country_city_names_dict[country_name] = [city_name]

    available_country_city_names_list = [{
        'text': country_name,
        'children': [{
            'id': city_name + '; ' + country_name,
            'text': city_name,
        } for city_name in available_country_city_names_dict[country_name]]
    } for country_name in available_country_city_names_dict]
    available_country_city_names_json = mark_safe(json.dumps(available_country_city_names_list))

    context = {
        'posts': posts,
        'showing_results': showing_results,
        'form': form,
        'available_city_names': available_country_city_names_json,
    }
    return render(request, 'browse/posts.html', context=context)

def post(request, post_id):
    post = Post.objects.get(id=post_id)

    report_type_tags = post.tags.filter(type='report_type')
    if report_type_tags.exists():
        report_type_tag_name = report_type_tags.first().name
    else:
        report_type_tag_name = None

    report_impact_tag_names = [tag.name for tag in post.tags.filter(type='report_impact')]
    report_impact_tag_names_json = mark_safe(json.dumps(report_impact_tag_names))

    project_intention_tag_names = [tag.name for tag in post.tags.filter(type='project-intention')]
    project_intention_tag_names_json = mark_safe(json.dumps(project_intention_tag_names))

    context = {
        'post': post,
        'report_type': report_type_tag_name,
        'report_impact_tag_names': report_impact_tag_names_json,
        'project_intention_tag_names': project_intention_tag_names_json,
        'formatted_timestamp': post.created_at.strftime(f'%B {post.created_at.day}, %Y'),
    }
    return render(request, 'browse/post.html', context=context)

def profile(request, user_id):
    user = User.objects.get(id=user_id)
    context = {
        'user': user,
        'posts': user.post_set.all(),
    }
    return render(request, 'browse/profile.html', context=context)

browse/templates/browse/old_post.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static 'browse/css/post_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static 'common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript'>
    var tagNames = {{ tag_names }};
    var supported = {{ supported }};
    var supportUrl = {{ support_url }};
    var unsupportUrl = {{ unsupport_url }};
</script>
<script type='text/javascript' src='{% static 'browse/js/post_main.js' %}'></script>
{% endblock %}

{% block content %}
{% include 'common/header.html' %}
<div class='container-fluid'>
    <div id='post' class='main'>
        {% if post.first_image %}
        <img id='image' class='custom-shadow' src='{{ post.first_image.image.url }}' alt='author image'/>
        {% else %}
        <div id='no-image'>[No image provided]</div>
        {% endif %}
        <div id='author-info' class='custom-shadow'>
            {% if post.user.profile.user_image_or_none %}
            <img id='author-image' src='{{ post.user.profile.user_image_or_none.image.url }}' alt='author image'/>
            {% else %}
            <div id='author-no-image'>[No image provided]</div>
            {% endif %}
            <div id='other-author-info'>
                <a href='{% url 'browse:profile' user_id=post.user.id %}' class='button'><div id='author-name' class='custom-shadow'>{{ post.user.profile.name }}</div></a>
                <div id='author-country'>{{ post.city.country.name }}</div>
            </div>
        </div>
        <!-- <div id='timestamp-wrapper'> -->
        <div id='timestamp'>{{ formatted_timestamp }}</div>
            <!-- <div id='supports'>{ post.n_supporters }</div> -->
    <!-- <div id='title'>{ post.title }</div> -->
        <!-- { if tag_names != '[]' }
        <div id='tags'></div>
        { endif } -->
        <div id='other-info'>
            {% if post.type == 'extreme_weather_report' %}
            <div id='type-title'><span id='type'>Extreme weather report: </span><span id='title'>{{ post.title }}</span></div>
            {% elif post.type == 'resilience_project' %}
            <div id='type-title'><span id='type'>Resilience project: </span><span id='title'>{{ post.title }}</span></div>
            {% elif post.type == 'climate_justice_event' %}
            <div id='type-title'><span id='type'>Climate justice event: </span><span id='title'>{{ post.title }}</span></div>
            {% elif post.type == 'well_needed' %}
            <div id='type-title'><span id='type'>Well needed: </span><span id='title'>{{ post.title }}</span></div>
            {% endif %}
        </div>
        <div id='text' class='custom-shadow'>{{ post.text }}</div>
    </div>
    <!-- <div id='post-footer' class='custom-shadow'>
        <div id='footer-bookend-left'></div>
        <a href='{% url 'browse:posts' %}'><div id='back-button'>
            <img id='back-icon' src='{% static 'browse/img/back_icon_grey.png' %}' alt='back icon'/>
            <span id='back-text'>Back</span>
        </div></a>
        <div id='support-button'>
            <img id='support-icon' src='{ static 'browse/img/support_icon_grey.png' }' alt='support icon'/>
            <span id='support-text'>Support</span>
        </div>
        <div id='unsupport-button'>
            <img id='unsupport-icon' src='{ static 'common/img/heart_icon_red.png' }' alt='unsupport icon'/>
            <span id='unsupport-text'>Unsupport</span>
        </div>
        <div id='reply-button'>
            <img id='reply-icon' src='{ static 'browse/img/reply_icon_grey.png' }' alt='reply icon'/>
            <span id='reply-text'>Reply</span>
        </div>
        <div id='next-button'>
            <img id='next-icon' src='{ static 'browse/img/next_icon_grey.png' }' alt='next icon'/>
            <span id='next-text'>Next</span>
        </div>
        <div id='footer-bookend-right'></div>
    </div> -->
</div>
{% endblock %}

browse/templates/browse/post.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static 'browse/css/post_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static 'common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript'>
    var reportImpactTagNames = {{ report_impact_tag_names }};
    var projectIntentionTagNames = {{ project_intention_tag_names }};
    // var supported = {{ supported }};
    // var supportUrl = {{ support_url }};
    // var unsupportUrl = {{ unsupport_url }};
</script>
<script type='text/javascript' src='{% static 'browse/js/post_main.js' %}'></script>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='post' class='main'>
        {% if post.first_image %}
        <img id='image' class='custom-shadow' src='{{ post.first_image.image.url }}' alt='author image'/>
        {% else %}
        <div id='no-image'>[No image provided]</div>
        {% endif %}
        <div id='author-info' class='custom-shadow'>
            {% if post.user.profile.user_image_or_none %}
            <img id='author-image' src='{{ post.user.profile.user_image_or_none.image.url }}' alt='author image'/>
            {% else %}
            <img id='author-image' src='{% static 'browse/img/default_profile_greengold.png' %}' alt='author image'/>
            <!-- <div id='author-no-image'>[No image provided]</div> -->
            {% endif %}
            <div id='other-author-info'>
                <a href='{% url 'browse:profile' user_id=post.user.id %}' class='button'><div id='author-name' class='custom-shadow'>{{ post.user.profile.name }}</div></a>
                <div id='author-country'>{{ post.city.country.name }}</div>
            </div>
        </div>
        <!-- <div id='timestamp-wrapper'> -->
        <div id='timestamp'>{{ formatted_timestamp }}</div>
            <!-- <div id='supports'>{ post.n_supporters }</div> -->
        <!-- { if tag_names != '[]' }
        <div id='tags'></div>
        { endif } -->
        <div id='other-info'>
            <div id='title'>{{ post.title }}</div>
            {% if post.type == 'extreme_weather_report' %}
            <div id='main-type'>Extreme weather report</div>
            <ul id='type-info-list'>
                <li>Event type: <span id='report-type'>{{ report_type }}</span></li>
                {% if report_impact_tag_names != '[]' %}
                <li><div id='report-impacts-text'>Event impacts: </div><div id='report-impacts'></div></li>
                {% endif %}
            </ul>
            {% elif post.type == 'resilience_project' %}
            <div id='main-type'>Resilience project</div>
            <ul id='type-info-list'>
                {% if project_intention_tag_names != '[]' %}
                <li><div id='project-intentions-text'>Project intentions: </div><div id='project-intentions'></div></li>
                {% endif %}
            </ul>
            <div id='project-intentions'></div>
            {% elif post.type == 'climate_justice_event' %}
            <div id='main-type'>Climate justice event</div>
            <ul id='type-info-list'>
                <li>Event date: <span id='event-date'>{{ post.event_date }}</span></li>
            </ul>
            {% elif post.type == 'well_needed' %}
            <div id='main-type'>Well needed</div>
            <ul id='type-info-list'>
                <li>Population served: <span id='well-population'>{{ post.well_population }}</span></li>
                <li>Amount needed (USD): <span id='well-amount'>${{ post.well_amount }}</span></li>
            </ul>
            {% endif %}
        </div>
        <div id='text' class='custom-shadow'>{{ post.text }}</div>
    </div>
    <!-- <div id='post-footer' class='custom-shadow'>
        <div id='footer-bookend-left'></div>
        <a href='{% url 'browse:posts' %}'><div id='back-button'>
            <img id='back-icon' src='{% static 'browse/img/back_icon_grey.png' %}' alt='back icon'/>
            <span id='back-text'>Back</span>
        </div></a>
        <div id='support-button'>
            <img id='support-icon' src='{ static 'browse/img/support_icon_grey.png' }' alt='support icon'/>
            <span id='support-text'>Support</span>
        </div>
        <div id='unsupport-button'>
            <img id='unsupport-icon' src='{ static 'common/img/heart_icon_red.png' }' alt='unsupport icon'/>
            <span id='unsupport-text'>Unsupport</span>
        </div>
        <div id='reply-button'>
            <img id='reply-icon' src='{ static 'browse/img/reply_icon_grey.png' }' alt='reply icon'/>
            <span id='reply-text'>Reply</span>
        </div>
        <div id='next-button'>
            <img id='next-icon' src='{ static 'browse/img/next_icon_grey.png' }' alt='next icon'/>
            <span id='next-text'>Next</span>
        </div>
        <div id='footer-bookend-right'></div>
    </div> -->
</div>
{% endblock %}

browse/templates/browse/post_preview.html
{% load static %}

<div class='post-wrapper'>
    <p class='post-timestamp'>{{ post.created_at }}</p>
    <a href='{% url 'browse:post' post_id=post.id %}'>
        <div class='post custom-shadow'>
            <div class='post-header'>
                <div class='post-header-left'>
                    {% if post.user.profile.user_image_or_none %}
                    <img class='author-image' src='{{ post.user.profile.user_image_or_none.image.url }}' alt='author image'/>
                    {% else %}
                    <img class='author-image' src='{% static 'browse/img/default_profile_greengold.png' %}' alt='author image'/>
                    <!-- <div class='author-no-image'>[No image provided]</div> -->
                    {% endif %}
                </div>
                <div class='post-header-right'>
                    <div class='author-name-country'><span class='author-name'>{{ post.user.profile.name }}</span><span class='author-country'>{{ post.user.profile.default_city.country.name }}</span></div>
                    <div class='title'>{{ post.title }}</div>
                </div>
            </div>
            {% if post.first_image and post.first_image.image %}
            <div class='post-body'>
                <div class='post-body-left'>
                    <img class='post-image' src='{{ post.first_image.image.url }}' alt='post image'/>
                </div>
                <div class='post-body-right'>
                    <p class='post-text'>{{ post.text }}</p>
                </div>
            </div>
            {% else %}
            <div class='post-body-spanning'>
                <p class='post-text-spanning'>{{ post.text }}</p>
            </div>
            {% endif %}
        </div>
    </a>
</div>

browse/templates/browse/posts.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'common/css/lib/selectivity-jquery.min.css' %}'>
<link rel='stylesheet' href='{% static 'browse/css/posts_style.css' %}'>
<link rel='stylesheet' href='{% static 'browse/css/post_preview_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript' src='{% static 'common/js/lib/selectivity-jquery.min.js' %}'></script>
<script type='text/javascript' src='{% static 'browse/js/posts_main.js' %}'></script>
<script type='text/javascript'>
    var availableCityNames = {{ available_city_names }};
</script>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='posts' class='main'>
        {% if showing_results %}
        {% if posts|length == 1 %}
        <div id='showing-results-banner' class='custom-shadow'>{{ posts|length }} result found:</div>
        {% else %}
        <div id='showing-results-banner' class='custom-shadow'>{{ posts|length }} results found:</div>
        {% endif %}
        {% endif %}
        {% if posts %}
        {% for post in posts %}
        {% include 'browse/post_preview.html' with post=post %}
        {% endfor %}
        {% endif %}
    </div>
    <div id='posts-footer' class='custom-shadow'>
        <form id='search-form' action='{% url 'browse:posts' %}' method='post'>
            {% csrf_token %}
            <input type='hidden' id='city-input-hidden' name='city'>
            <div id='footer-bars'>
                <div id='search-bar' class='bar'>
                    <div id='search-icon-wrapper'>
                        <img id='search-icon' src='{% static 'common/img/search_gold.png' %}' alt='search icon'/>
                    </div>
                    <div id='search-input-wrapper'>
                        {{ form.query }}
                    </div>
                    {{ form.query.errors }}
                </div>
                <div id='city-bar' class='bar bar-extra'>
                    <!-- <div id='location-bar-dropdown'>Location &#9662;</div> -->
                    <div id='city'></div>
                    {{ form.city.errors }}
                </div>
                <div id='type-bar' class='bar bar-extra'>
                    {{ form.type }}
                    {{ form.type.errors }}
                </div>
                <div id='sort-bar' class='bar bar-extra'>
                    <!-- <div id='sort-bar-dropdown'>Sort by &#9662;</div> -->
                    {{ form.sort_by }}
                    {{ form.sort_by.errors }}
                </div>
                <div id='button-bar' class='bar bar-extra'>
                    <a href='{% url 'browse:posts' %}'><div id='clear-button'>Clear</div></a>
                    <button id='search-button' type='submit'>Search</button>
                </div>
            </div>
        </form>
        <div id='search-expand-icon-wrapper'>
            <img id='search-expand-icon' src='{% static 'common/img/expand_gold.png' %}' alt='search expand icon'/>
        </div>
        <div id='search-collapse-icon-wrapper'>
            <img id='search-collapse-icon' src='{% static 'common/img/collapse_gold.png' %}' alt='search collapse icon'/>
        </div>
    </div>
</div>
{% endblock %}

browse/templates/browse/profile.html
{% extends 'common/base.html' %}

{% block content_style %}
{% load static %}
<link rel='stylesheet' href='{% static 'browse/css/profile_style.css' %}'>
<link rel='stylesheet' href='{% static 'browse/css/post_preview_style.css' %}'>
{% endblock %}

{% block content_script %}
{% load static %}
<script type='text/javascript'>
    var supported = {{ supported }};
    var supportUrl = {{ support_url }};
    var unsupportUrl = {{ unsupport_url }};
</script>
<script type='text/javascript' src='{% static 'browse/js/profile_main.js' %}'></script>
{% endblock %}

{% block content %}
<div class='container-fluid'>
    <div id='profile-wrapper' class='main'>
        <div id='profile-header' class='custom-shadow'>
            <div id='profile-header-left'>
                {% if user.profile.user_image_or_none %}
                <img id='user-image' src='{{ user.profile.user_image_or_none.image.url }}' alt='user image'/>
                {% else %}
                <img id='user-image' src='{% static 'browse/img/default_profile_greengold.png' %}' alt='author image'/>
                <!-- <div id='no-user-image'>[No image provided]</div> -->
                {% endif %}
            </div>
            <div id='profile-header-right'>
                <div id='name'>{{ user.profile.name }}</div>
                {% if user.profile.website %}
                <div id='website' class='custom-shadow'>{{ user.profile.website }}</div>
                <!-- { else }
                <div id='no-website'>[No website provided]</div> -->
                {% endif %}
            </div>
        </div>
        <div id='profile-content'>
            {% if user.profile.bio %}
            <div id='profile-bio'>
                <div id='bio-title'>Bio</div>
                <div id='bio-text'>{{ user.profile.bio }}</div>
            </div>
            {% endif %}
            <div id='profile-posts'>
                <div id='user-posts-title'>Posts</div>
                {% if posts %}
                {% for post in posts %}
                {% include 'browse/post_preview.html' with post=post %}
                {% endfor %}
                {% else %}
                <div id='no-posts'>[No posts by this user]</div>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- <div id='profile-footer' class='custom-shadow'>
        <div id='back-button'>
            <img id='back-icon' src='{ static 'browse/img/back_icon_green.svg' }' alt='back icon'/>
            <span id='back-text'>Back</span>
        </div>
        <div id='support-button'>
            <img id='support-icon' src='{ static 'browse/img/support_icon_green.svg' }' alt='support icon'/>
            <span id='support-text'>Support</span>
        </div>
        <div id='unsupport-button'>
            <img id='unsupport-icon' src='{ static 'common/img/heart_icon_red.png' }' alt='unsupport icon'/>
            <span id='unsupport-text'>Unsupport</span>
        </div>
    </div> -->
</div>
{% endblock %}